[package]

name = "zip"
version = "0.2.6"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
documentation = "http://mvdnes.github.io/rust-docs/zip-rs/zip/index.html"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
flate2 = { git = "https://github.com/alexcrichton/flate2-rs", default-features = false }
time = "0.1"
podio = "0.1"
msdos_time = "0.1"
bzip2 = { version = "0.3", optional = true }

[dev-dependencies]
walkdir = "1.0"

[features]
default = ["bzip2", "flate2/default"]
rust_backend = ["flate2/rust_backend"]
