[package]
name = "zip"
version = "0.5.13"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>", "Marli Frost <marli@frost.red>", "Ryan Levick <ryan.levick@gmail.com>"]
license = "MIT"
repository = "https://github.com/zip-rs/zip.git"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""
edition = "2018"

[dependencies]
flate2 = { version = "1.0.0", default-features = false, optional = true }
time = { version = "0.3", features = ["formatting", "macros" ], optional = true }
byteorder = "1.3"
bzip2 = { version = "0.4", optional = true }
crc32fast = "1.1.1"
strum = "0.23.0"
strum_macros = "0.23.0"
zstd = { version = "0.10", optional = true }

[dev-dependencies]
criterion = "0.3.5"
getrandom = "0.2"
walkdir = "2"

[features]
deflate = ["flate2/rust_backend"]
deflate-miniz = ["flate2/default"]
deflate-zlib = ["flate2/zlib"]
unreserved = []
default = ["bzip2", "deflate", "time", "zstd"]

[[bench]]
name = "read_entry"
harness = false
