name: Auto-merge PRs from owner and trusted bots
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'github-actions' || github.actor == 'Pr0methean' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: dependabot/fetch-metadata@v2.1.0
        with:
          github-token: "${{ github.token }}"
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: "${{ secrets.RELEASE_PLZ_PAT }}"
